### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by sbrl** [MLAB-project/stl-thumbnailer#9]
Python 2 is no longer supported. To upgrade to Python 3, do this:

```bash
sudo apt install 2to3
2to3 --write stl_thumb.py
```

....but then I get this:

```
Traceback (most recent call last):
  File "/usr/local/bin/stl_thumb.py", line 44, in <module>
    main()
  File "/usr/local/bin/stl_thumb.py", line 15, in main
    m.update(fin)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by kaklik** [comment]
Resolved by @Smartich0ke
